### ISSUE TITLE
Module compiled with Swift 4.1.2 cannot be imported by the Swift 5.0.1 compiler

### ISSUE THREAD

**Issue by reddiny** [ob1y2k/publitio_ios_sdk#1]
When trying to compile my project (with Publitio as a cocoapod) I get the following error message: Module compiled with Swift 4.1.2 cannot be imported by the Swift 5.0.1 compiler.

**Comment by balsayegh** [comment]
Got the same issue, and had to search for another provider

**Comment by nitroy2k** [comment]
I am sorry we never saw this messages it is my fault possibly, but we have made update to support new compilers there are 2 versions available 'Publitio', '~> 1.2 < Latest' . and 'Publitio', '~> 1.1 ' < earlier version
that can be used, new version for 11.2 will come out in few days.
