### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by syonip** [ob1y2k/publitio_ios_sdk#2]
Library doesn't compile with XCode 11.2.1

```
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Users/johnny/git/flutter_video_sharing/ios/Pods/Publitio/Publitio.framework/Modules/Publitio.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```

According to [SO](https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler), the solution might be to add `BUILD_LIBRARY_FOR_DISTRIBUTION = YES` to `pbxproj` file of the library.

**Comment by nitroy2k** [comment]
The team has been dispatched to make update of SDK

**Comment by syonip** [comment]
Any progress on this?

**Comment by nitroy2k** [comment]
Update has been released https://github.com/ob1y2k/publitio_ios_sdk

**Comment by syonip** [comment]
Thanks, problem solved. Closing this.
I think you can also close #1
